baseURL: "https://podcast.kotet.jp"
languageCode: "ja-jp"
title: "Counter Memes Podcast"

params:
  feed:
    copyright: © 2019 Kotet - All Rights Reserved.
    itunes_subtitle: カウンターミーム ポッドキャスト
    itunes_author: Kotet
    itunes_summary: Counter Memes Podcastは愛知県立大学情報科学部生のKotetが作るPodcastです。
    itunes_owner_name: Kotet
    itunes_owner_email: kotet0418@gmail.com
    itunes_image: https://podcast.kotet.jp/img/itunes_image.jpg
    itunes_top_category: Technology
    itunes_first_sub_category: Podcasting
    explicit: no
  media_prefix: https://podcast.kotet.jp/audio/

taxonomies:
  categories: ""